init python:
    if persistent.FirstName == None:
        persistent.FirstName = "翔平"
    if persistent.LastName == None:
        persistent.LastName = "諏訪部"
    if persistent.IsFirstLaunch == None:
        persistent.IsFirstLaunch = True
    if persistent.SystemStoryCache == None:
        persistent.SystemStoryCache = [0] * 18
    if persistent.GClickWarningShown == None:
        persistent.GClickWarningShown = False
    if persistent.SYSMusicAvailable == None:
        persistent.SYSMusicAvailable = False
    if persistent.FirstChooseLanguage == None:
        persistent.FirstChooseLanguage = False
    FirstChooseLanguage = False
    SYSReviewMode = False
    SYSTheaterState = 0
    IsCaveMemoAvailable = False
    IsCaveRollbackAvailable = False
    Chapter = 0
    C0SShinobu = False
    C1S1 = False
    C1S2 = False
    C1S3 = False
    C1S4 = False
    C1S5 = False
    C1SSabuShin = False
    C2S1 = False
    C2S2 = False
    C2S3 = False
    C2S4 = False
    C2S5 = False
    C2S6 = False
    C2SNori = False
    C2SYuuhi = False
    C3S1 = False
    C3S2 = False
    C3S3 = False
    C3S4 = False
    C3S5 = False
    C3S6 = False
    C3SSabuShin = False
    C3SPark = False
    C3SPhoto = False
    C3SYukiToki = False
    C3SShiroYuki = False
    C1SG1 = False
    C1SG2 = False
    C2SG1 = False
    C2SG2 = False
    C3SG1 = False
    C3SG2 = False
    C1QNewsclub = False
    C1QKimuraConference = False
    C1QSabuShin = False
    C1QTsubasa = False
    C1QMatsuta = False
    C2QNewsclub = False
    C2QKimuraConference = False
    C2QYuuhi = False
    C2QSakuya = False
    C2QSora = False
    C3QNewsclub = False
    C3QKimuraConference = False
    C3QSakuyaWalk1 = False
    C3QSakuyaWalk2 = False
    C3QShiro = False
    C3QNakayama = False
    C3QYakyuken = False
    C3QNori = False
    GTsukiTestStage = 0
    GTsukiTestSoraMode = False
    GSabuImechenTomoState = 0
    GSabuImechenShintaroState = 0
    GSabuImechenShinobuState = 0
    GSabuImechenTsubasaState = 0
    GSabuImechenTsukiState = 0
    GSabuImechenSoraState = 0
    GSabuImechenSakuyaState = 0
    GSabuImechenSaburoState = 0
    GKarutaStage = 0
    GKarutaViewMode = False
    CXQShinoQuestion = False
    CXQSabuImechen = False
    CXQTsukiTest = False
    CXQKaruta = False
    FTokiwaHelp = True
    FNewsclub = True
    FTheater = True
    FEnterMisaki = True
    FEnterDream = True
    END = False
